# Generated by Django 5.1.2 on 2024-10-12 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('user_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_first_name', models.CharField(max_length=30)),
                ('user_middle_name', models.CharField(blank=True, max_length=30)),
                ('user_last_name', models.CharField(max_length=30)),
                ('user_dob', models.DateField()),
                ('user_phone_number', models.BigIntegerField()),
                ('user_password', models.CharField()),
                ('user_status', models.BooleanField(default=False)),
                ('user_hold', models.BooleanField(default=False)),
                ('user_type', models.CharField()),
                ('profile_privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_first_name', models.CharField(max_length=30)),
                ('user_middle_name', models.CharField(blank=True, max_length=30)),
                ('user_last_name', models.CharField(max_length=30)),
                ('user_dob', models.DateField()),
                ('user_phone_number', models.BigIntegerField()),
                ('user_country', models.CharField(max_length=50)),
                ('user_city', models.CharField(max_length=50)),
                ('user_address_line_1', models.CharField(max_length=255)),
                ('user_address_line_2', models.CharField(max_length=255)),
                ('user_pin_code', models.BigIntegerField()),
                ('user_state', models.CharField(max_length=50)),
                ('user_profile_photo', models.CharField(blank=True, max_length=255, null=True)),
                ('user_password', models.CharField(max_length=255)),
                ('user_type', models.CharField(default='customer', max_length=50)),
                ('user_old_password', models.CharField(blank=True, max_length=128, null=True)),
                ('user_joined_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('last_login', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('users_daily_limit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('users_monthly_limit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionUser',
            fields=[
                ('transaction_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('transaction_timestamp', models.DateTimeField()),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(max_length=50)),
                ('user_phone_number', models.BigIntegerField()),
                ('transaction_currency', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'transaction_table',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='walletadminactions',
            name='admins_actions_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
