# Generated by Django 5.1.2 on 2024-10-12 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCMS',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(blank=True, max_length=100, null=True)),
                ('currency_type', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'admincms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_first_name', models.CharField(max_length=30)),
                ('user_middle_name', models.CharField(blank=True, max_length=30)),
                ('user_last_name', models.CharField(max_length=30)),
                ('user_dob', models.DateField()),
                ('user_phone_number', models.BigIntegerField()),
                ('user_country', models.CharField(max_length=50)),
                ('user_city', models.CharField(max_length=50)),
                ('user_profile_photo', models.FileField(blank=True, null=True, upload_to='profile_photos/')),
                ('user_address_line_1', models.CharField()),
                ('user_password', models.CharField()),
                ('user_status', models.BooleanField(default=False)),
                ('user_hold', models.BooleanField(default=False)),
                ('user_type', models.CharField()),
                ('user_state', models.CharField()),
                ('user_pin_code', models.CharField()),
                ('profile_privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FiatWallet',
            fields=[
                ('fiat_wallet_id', models.CharField(blank=True, max_length=12)),
                ('fiat_wallet_address', models.CharField(blank=True, max_length=255)),
                ('fiat_wallet_type', models.CharField(max_length=50)),
                ('fiat_wallet_currency', models.CharField(max_length=10)),
                ('fiat_wallet_balance', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('fiat_wallet_created_time', models.DateTimeField(auto_now_add=True)),
                ('fiat_wallet_updated_time', models.DateTimeField(auto_now=True)),
                ('fiat_wallet_phone_number', models.CharField(blank=True, max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Invalid phone number format.', regex='^\\+?1?\\d{9,15}$')])),
                ('fiat_wallet_email', models.EmailField(max_length=254)),
                ('user_id', models.CharField(max_length=255)),
                ('qr_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fiat_wallet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('wallet_id', models.CharField(max_length=255)),
                ('transaction_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('transaction_timestamp', models.DateField()),
                ('transaction_type', models.CharField(max_length=255)),
                ('transaction_amount', models.CharField(max_length=255)),
                ('transaction_status', models.CharField()),
            ],
            options={
                'db_table': 'transaction_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionUser',
            fields=[
                ('wallet_id', models.CharField(max_length=255)),
                ('transaction_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('transaction_timestamp', models.DateTimeField()),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(max_length=50)),
                ('user_phone_number', models.BigIntegerField()),
                ('transaction_currency', models.CharField(max_length=3)),
                ('transaction_status', models.CharField()),
            ],
            options={
                'db_table': 'transaction_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserCurrency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wallet_id', models.CharField(max_length=255)),
                ('currency_type', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
            ],
            options={
                'db_table': 'user_currencies',
                'managed': False,
            },
        ),
    ]
